[project]
name = "pyrdata-meetup-marimo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "marimo>=0.16.5",
]
